POST https://test-code-deploying.vercel.app/user/app
Content-Type: application/json

{   
    "username":"dd",
    "password":"asdaf",
    "email":"hello",
    "photoURL":""
}
###
DELETE  https://test-code-deploying.vercel.app/user/api


